// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-ipaT0RdQcgfC3kLDULLOZ-QTs6lWPo8',
    appId: '1:511570380831:web:2ba30b0e727a6f6b49ed2a',
    messagingSenderId: '511570380831',
    projectId: 'jivan-swad-app',
    authDomain: 'jivan-swad-app.firebaseapp.com',
    storageBucket: 'jivan-swad-app.firebasestorage.app',
    measurementId: 'G-1534ZTZN6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVcwwHZyroT4XqOpygPx-mJHxPupXevDA',
    appId: '1:511570380831:android:f980511825f872c849ed2a',
    messagingSenderId: '511570380831',
    projectId: 'jivan-swad-app',
    storageBucket: 'jivan-swad-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfdN9Yq8whS3EpLhir_PwFk4W1yyMHmas',
    appId: '1:511570380831:ios:6c175f8f58803ef549ed2a',
    messagingSenderId: '511570380831',
    projectId: 'jivan-swad-app',
    storageBucket: 'jivan-swad-app.firebasestorage.app',
    iosBundleId: 'com.example.jivanSwadApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfdN9Yq8whS3EpLhir_PwFk4W1yyMHmas',
    appId: '1:511570380831:ios:6c175f8f58803ef549ed2a',
    messagingSenderId: '511570380831',
    projectId: 'jivan-swad-app',
    storageBucket: 'jivan-swad-app.firebasestorage.app',
    iosBundleId: 'com.example.jivanSwadApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-ipaT0RdQcgfC3kLDULLOZ-QTs6lWPo8',
    appId: '1:511570380831:web:e5ff1777572f028149ed2a',
    messagingSenderId: '511570380831',
    projectId: 'jivan-swad-app',
    authDomain: 'jivan-swad-app.firebaseapp.com',
    storageBucket: 'jivan-swad-app.firebasestorage.app',
    measurementId: 'G-80406YHPHR',
  );

}